package ivocabulary


type ServiceGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	VocabularyInfoService
	VocabularyWordsService
	WordInfoService
	WordEgsService
	EgInfoService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

