package ivocabulary

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	VocabularyInfoRouter
	VocabularyWordsRouter
	WordInfoRouter
	WordEgsRouter
	EgInfoRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
