package ivocabulary

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	VocabularyInfoApi
	VocabularyWordsApi
	WordInfoApi
	WordEgsApi
	EgInfoApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
